kind = "mobile"
previewPath = "/"
title = "ZeroRisco"
version = "1.0.0"
id = "artifacts/zerorisco"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23996

[services.development]
run = "pnpm --filter @workspace/zerorisco run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zerorisco", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/zerorisco", "run", "serve" ]

[services.env]
PORT = "23996"
BASE_PATH = "/"
